In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets

In [3]:
import numpy as np

k1 = np.array([[5,10,15],
               [2,4,6],
               [1,3,5]])
k2 = np.array([100])
k3 = np.array([[100],
              [100],
              [100]])
print(k1)
print(k2)
print(k3)

[[ 5 10 15]
 [ 2  4  6]
 [ 1  3  5]]
[100]
[[100]
 [100]
 [100]]


In [4]:
#簡單計算

x = [10,20,30]

print(x+[40,50])#list 合併元素

y = np.array(x)#將list轉成array去做計算
print(y+[40,50,60])#numpy會自動推播數量再進行計算

[10, 20, 30, 40, 50]
[50 70 90]


In [5]:
A = np.array([10,10,10])
print(type(A))
print(A+10)

<class 'numpy.ndarray'>
[20 20 20]


In [6]:
a4 = np.array([11,12,13,14,15,16])
a5 = np.array([[1,2,3,4],
               [11,12,13,14],
               [21,22,23,24]])
#結構
print(a4.shape)
print(a5.shape)

(6,)
(3, 4)


In [7]:
#改變結構
print(a4.reshape(2,3))
print(a4)
print('-------------------')

print(a4.reshape(3,-1))# -1代表自動調整計算
print(a4.reshape(-1,2))

print(a5.reshape(6,-1))# -1代表自動調整計算
print(a5.reshape(-1,12))

[[11 12 13]
 [14 15 16]]
[11 12 13 14 15 16]
-------------------
[[11 12]
 [13 14]
 [15 16]]
[[11 12]
 [13 14]
 [15 16]]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]
 [21 22]
 [23 24]]
[[ 1  2  3  4 11 12 13 14 21 22 23 24]]


In [8]:
#轉成一維
print(a5.reshape(-1))

[ 1  2  3  4 11 12 13 14 21 22 23 24]


In [9]:
#讀取元素
x = np.array([[86,75,89],
              [77,62,81],
              [82,69,85]]) 
#指定單一位置，若位置不存在則出錯
print(x[0])
#print(x[5])
print(x[0][2])
print(x[0,2])

[86 75 89]
89
89


In [10]:
#slice 範圍選取，若位置不存在則返回[]
print(x[:2])
print('----------------')
print(x[0][1:2])
print(x[0][1: ])
print(x[0][10:30])
print(x[0][:20])
print('----------------')
print(x[:])
print(x)
print('----------------')
print(x[0,0:2])
print(x[:2, 1:])

[[86 75 89]
 [77 62 81]]
----------------
[75]
[75 89]
[]
[86 75 89]
----------------
[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]
 [82 69 85]]
----------------
[86 75]
[[75 89]
 [62 81]]


In [11]:
#slice 範圍選取，若位置不存在則返回[]
print(x)
print(x[:2])
print('----------------')
print(x[0][1:2])
print(x[0][1: ])
print(x[0][10:30])
print(x[0][:20])
print('----------------')
print(x[:])
print(x)
print('----------------')
print(x[0,0:2])
print(x[:2, 1:])

[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]]
----------------
[75]
[75 89]
[]
[86 75 89]
----------------
[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]
 [82 69 85]]
----------------
[86 75]
[[75 89]
 [62 81]]


In [12]:
# 亂數
np.random.seed(123)#固定亂數規則(基數)

arr0 = np.random.randint(0, 11)#0-11(有包含11)之間產生一個隨機整數
print(arr0)
arr00 = np.random.randint(0, 11, 3)#0-11(有包含11)之間產生3個隨機整數
print(arr00)

arr1 = np.random.randint(0, 11, (5, 2))# 5*2個
print('arr1:')
print(arr1)
print("-----------------------")

arr2 = np.random.rand(3)# 3個隨機小數，0-1之間(不含 1)
print('arr2:')
print(arr2)

2
[2 6 1]
arr1:
[[ 3 10]
 [ 9  6]
 [ 1  0]
 [ 1  9]
 [ 0  0]]
-----------------------
arr2:
[0.72904971 0.43857224 0.0596779 ]


In [22]:
np.random.seed(0)#隨機選
x = ['蘋果', '橘子', '香蕉', '鳳梨', '奇異果', '草莓']
print(np.random.choice(x,3))#隨機選三個


['奇異果' '草莓' '蘋果']


In [23]:
# 條件套用
arr = np.arange(10)#產生0~9的整數(小於10的整數)

new_arr = arr%5==0
print(arr)
print(new_arr)
print(arr[new_arr])

[0 1 2 3 4 5 6 7 8 9]
[ True False False False False  True False False False False]
[0 5]


In [24]:
arr = np.array([4, -9, 16, -4, 20])
print(arr)
arr_abs = np.abs(arr)
print('絕對值:',arr_abs)
print('e為底數:',np.exp(arr_abs))
print('平方根:',np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
絕對值: [ 4  9 16  4 20]
e為底數: [5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
平方根: [2.         3.         4.         2.         4.47213595]


In [28]:
b1 = np.array(np.arange(9).reshape(3,-1))
print(b1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
print(np.sum(b1))
print(np.sum(b1, axis=0))#垂直向下
print(np.sum(b1, axis=1))#水平向右

36
[ 9 12 15]
[ 3 12 21]


In [31]:
print(b1)
print(sum(b1))#python內建函式,垂直

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [32]:
print("垂直加總：",np.sum(b1, axis=0))
print("橫向加總：",np.sum(b1, axis=1))
print("------------------------------------")
print("加總：",b1.sum(axis=0))

print("平均：",np.mean(b1, axis=0))
print("中位數：",np.median(b1, axis=0))
#離群值很少==>用平均
#離群值很多==>用中位數

print("變異數：",np.var(b1, axis=0))
print("標準差：",np.std(b1, axis=0))

print("------------------------------------")

print("最大值：",np.max(b1, axis=0))
print("最小值：",np.min(b1, axis=0))

print("差距：",np.ptp(b1, axis=0))

垂直加總： [ 9 12 15]
橫向加總： [ 3 12 21]
------------------------------------
加總： [ 9 12 15]
平均： [3. 4. 5.]
中位數： [3. 4. 5.]
變異數： [6. 6. 6.]
標準差： [2.44948974 2.44948974 2.44948974]
------------------------------------
最大值： [6 7 8]
最小值： [0 1 2]
差距： [6 6 6]
