In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets

In [3]:
import numpy as np

k1 = np.array([[5,10,15],
               [2,4,6],
               [1,3,5]])
k2 = np.array([100])
k3 = np.array([[100],
              [100],
              [100]])
print(k1)
print(k2)
print(k3)

[[ 5 10 15]
 [ 2  4  6]
 [ 1  3  5]]
[100]
[[100]
 [100]
 [100]]


In [4]:
#簡單計算

x = [10,20,30]

print(x+[40,50])#list 合併元素

y = np.array(x)#將list轉成array去做計算
print(y+[40,50,60])#numpy會自動推播數量再進行計算

[10, 20, 30, 40, 50]
[50 70 90]


In [5]:
A = np.array([10,10,10])
print(type(A))
print(A+10)

<class 'numpy.ndarray'>
[20 20 20]


In [6]:
a4 = np.array([11,12,13,14,15,16])
a5 = np.array([[1,2,3,4],
               [11,12,13,14],
               [21,22,23,24]])
#結構
print(a4.shape)
print(a5.shape)

(6,)
(3, 4)


In [7]:
#改變結構
print(a4.reshape(2,3))
print(a4)
print('-------------------')

print(a4.reshape(3,-1))# -1代表自動調整計算
print(a4.reshape(-1,2))

print(a5.reshape(6,-1))# -1代表自動調整計算
print(a5.reshape(-1,12))

[[11 12 13]
 [14 15 16]]
[11 12 13 14 15 16]
-------------------
[[11 12]
 [13 14]
 [15 16]]
[[11 12]
 [13 14]
 [15 16]]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]
 [21 22]
 [23 24]]
[[ 1  2  3  4 11 12 13 14 21 22 23 24]]


In [8]:
#轉成一維
print(a5.reshape(-1))

[ 1  2  3  4 11 12 13 14 21 22 23 24]


In [9]:
#讀取元素
x = np.array([[86,75,89],
              [77,62,81],
              [82,69,85]]) 
#指定單一位置，若位置不存在則出錯
print(x[0])
#print(x[5])
print(x[0][2])
print(x[0,2])

[86 75 89]
89
89


In [10]:
#slice 範圍選取，若位置不存在則返回[]
print(x[:2])
print('----------------')
print(x[0][1:2])
print(x[0][1: ])
print(x[0][10:30])
print(x[0][:20])
print('----------------')
print(x[:])
print(x)
print('----------------')
print(x[0,0:2])
print(x[:2, 1:])

[[86 75 89]
 [77 62 81]]
----------------
[75]
[75 89]
[]
[86 75 89]
----------------
[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]
 [82 69 85]]
----------------
[86 75]
[[75 89]
 [62 81]]


In [11]:
#slice 範圍選取，若位置不存在則返回[]
print(x)
print(x[:2])
print('----------------')
print(x[0][1:2])
print(x[0][1: ])
print(x[0][10:30])
print(x[0][:20])
print('----------------')
print(x[:])
print(x)
print('----------------')
print(x[0,0:2])
print(x[:2, 1:])

[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]]
----------------
[75]
[75 89]
[]
[86 75 89]
----------------
[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]
 [82 69 85]]
----------------
[86 75]
[[75 89]
 [62 81]]


In [12]:
# 亂數
np.random.seed(123)#固定亂數規則(基數)

arr0 = np.random.randint(0, 11)#0-11(有包含11)之間產生一個隨機整數
print(arr0)
arr00 = np.random.randint(0, 11, 3)#0-11(有包含11)之間產生3個隨機整數
print(arr00)

arr1 = np.random.randint(0, 11, (5, 2))
print('arr1:')
print(arr1)
print("-----------------------")
arr2 = np.random.rand(3)# 3個隨機小數，0-1之間(不含 1)
print('arr2:')
print(arr2)

2
[2 6 1]
arr1:
[[ 3 10]
 [ 9  6]
 [ 1  0]
 [ 1  9]
 [ 0  0]]
-----------------------
arr2:
[0.72904971 0.43857224 0.0596779 ]
