In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets

In [4]:
import numpy as np

k1 = np.array([[5,10,15],
               [2,4,6],
               [1,3,5]])
k2 = np.array([100])
k3 = np.array([[100],
              [100],
              [100]])
print(k1)
print(k2)
print(k3)

[[ 5 10 15]
 [ 2  4  6]
 [ 1  3  5]]
[100]
[[100]
 [100]
 [100]]
